// 定义 Action 为常量，防止出错

export const SEARCH_FOCUS = "SEARCH_FOCUS";
export const SEARCH_BLUR = "SEARCH_BLUR";
export const NAV_ACTIVE_HOME = "NAV_ACTIVE_HOME";
export const NAV_ACTIVE_TECHNOLOGY = "NAV_ACTIVE_TECHNOLOGY";
export const NAV_ACTIVE_PROJECT = "NAV_ACTIVE_PROJECT";
export const NAV_ACTIVE_PHOTO = "NAV_ACTIVE_PHOTO";
